name:                sfmt-mod
version:             0.1.0.0
github:              "mskmysht/sfmt-hs"
license:             BSD3
author:              "Masaaki Miyashita"
maintainer:          "m.mysht118@gmail.com"
copyright:           "2019 Masaaki Miyashtia, 2014 HirotomoMoriwaki"

extra-source-files:
- SFMT-src-1.4.1/SFMT.h
- SFMT-src-1.4.1/SFMT-sse2.h
- SFMT-src-1.4.1/SFMT-common.h
- SFMT-src-1.4.1/SFMT-params.h
- SFMT-src-1.4.1/SFMT-params19937.h

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mskmysht/sfmt-hs#readme>

dependencies:
- base       >=4.7  && <5
- primitive  >=0.5  && <0.7
- bytestring >=0.10 && <0.11
- entropy    >=0.3  && <0.5

library:
  source-dirs: ./
  c-sources:
  - SFMT-src-1.4.1/SFMT.c
  - cbits/wrap.c

executables:
  sfmt-mod-exe:
    main:                MonteCarlo.hs
    source-dirs:         examples
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sfmt-mod

